### ISSUE TITLE
is null, not null and not equal filter

### ISSUE THREAD

**Issue by maceonrails** [kollegorna/active_hash_relation#14]
Hi, thanks for create this great gem. btw how to filter for 'is null' or 'not null' condition? and i think not equal (:neq) filter is not yet available, is it?

**Comment by vasilakisfil** [comment]
Hi! Unfortunately there is no such filter. Not equal is scheduled for Version 2 (https://github.com/kollegorna/active_hash_relation/issues/13). About null, I have also thought about it a lot I think I should also include that to Version 2.

**Comment by vasilakisfil** [comment]
Hi!
Null/not null filter has been implemented on #16 
Not filter has been just added on #25

You need to use version 1.3.0+ in order to get them (or use master). Enjoy!
