### ISSUE TITLE
ActiveRecord::Type is undefined

### ISSUE THREAD

**Issue by firstsano** [kollegorna/active_hash_relation#18]
Hi, first of all - great gem, thanks for great work!
Secondary, I run into a problem, that `ActiveRecord::Type is undefined`. So I've found out that the problem is that I was using `active_record 4.1.2` but `ActiveRecord::Type` is presented inly in 4.2.0. So my question is - should there be a dependency during gem installation? Feel free to close this issue, if I'm wrong. Thanks!

**Comment by vasilakisfil** [comment]
hi @firstsano! It seems you are right. There should be a dependency around ActiveRecord. I will fix it later this week. In the meantime, do you need support for AR 4.1 ?

**Comment by firstsano** [comment]
No worries, I've just updated to 4.2.0 and everything works like a charm!
