### ISSUE TITLE
Rails 5 boolean type_cast_from_database to cast

### ISSUE THREAD

**Issue by KRaymundus** [kollegorna/active_hash_relation#21]
According to my error message and what I read [here](http://stackoverflow.com/a/25514105/3071369): In Rails 5, the boolean casting is to be done as:
`ActiveRecord::ConnectionAdapters::Column.cast(param)`
instead of:
`ActiveRecord::ConnectionAdapters::Column.type_cast_from_database(param)`

So the `filter_boolean` function in column_filters.rb should become:
```
def filter_boolean(resource, column, param)
  b_param = ActiveRecord::Type::Boolean.new.cast(param)

  resource = resource.where(column => b_param)
end
```

**Comment by vasilakisfil** [comment]
@KRaymundus you are correct. I am adding tests on branch feat/tests and I will incorporate this by checking AR version. I will probably finish with adding tests end of this week and close this issue :)

**Comment by vasilakisfil** [comment]
Fixed on master, closing.
