### ISSUE TITLE
ActiveRecord::ConnectionAdapters::Column.value_to_boolean deprecated

### ISSUE THREAD

**Issue by alinbsp** [kollegorna/active_hash_relation#8]
value_to_boolean used by filter_boolean has been deprecated from rails.

**Comment by persand** [comment]
@alinbsp Thanks for reporting! Can you do a pull request?

**Comment by alinbsp** [comment]
Sure, I'll do it over the weekend.

**Comment by persand** [comment]
Great. Thanks!

**Comment by vasilakisfil** [comment]
Fixed in #9
